name: Build/Push App for Production
on:
  push:
    branches:
      - main

env:
  IMAGE_BASE: ${{ vars.LOCAL_ACR_URL }}/${{ vars.LOCAL_ACR_USERNAME }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT

      - name: Login to Local ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.LOCAL_ACR_URL }}
          username: ${{ vars.LOCAL_ACR_USERNAME }}
          password: ${{ secrets.LOCAL_ACR_PASSWORD }}

      - name: Build & Push to Local ACR
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
          push: true
          build-args: |
            OS_VERSION=${{ env.UBUNTU_VERSION }}
            ARCH=${{ matrix.architecture }}
          tags: |
            ${{ env.IMAGE_BASE }}/${{ steps.meta.outputs.REPO_NAME }}:latest

  report:
    name: Report
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - release
    # uses: adam/gitea-workflows/.gitea/workflows/notify.yaml@main
    steps:
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT

      - name: Report of Success
        if: needs.release.result == 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ✅ Released ${{ steps.meta.outputs.REPO_NAME }}:latest app!

      - name: Report of Failure
        if: needs.release.result != 'success'
        uses: umahmood/pushover-actions@main
        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        with:
          title: Gitea DevOps
          message: ❌ Unable to release ${{ steps.meta.outputs.REPO_NAME }}:latest app.
